TRAINING:
  # Labels must be two values of type string separated by commas.
  LABELS: Good,Damaged
  # Targeted image size. It must be two values(width and height), both an integer type, separated by commas.
  # Because of MobileNet-v2's requirements it can only be: 96 or 128 or 160 or 192 or 224
  IMG_SHAPE: 224,224
  # Base learning rate must be of type float.
  BASE_LEARNING_RATE: 0.0001
  # Epochs must be of type integer (greater than 0).
  EPOCHS: 10
  # Batch size must be of type integer (greater than 0).
  BATCH_SIZE: 7
  # Membership boundary must be of type float and be between 0 and 1.
  MEMBERSHIP_BOUNDARY: 0.5